
- hosts: localhost
  tasks:
    - name: Retrieve secret from Conjur
      debug:
        msg: "Yay! {{ ansible_env.CYBERARK_DB_USERNAME}}:{{ ansible_env.CYBERARK_DB_PASSWORD}} was just retrieved via Conjur"
